_test_extensions_category:
    resource: @GedmoDemoBundle/Controller/CategoryController.php
    type:     annotation
    prefix:   /category

_test_extensions_language:
    resource: @GedmoDemoBundle/Controller/LanguageController.php
    type:     annotation
    prefix:   /language
    
_default_test_index:
    pattern:  /
    defaults: { _controller: GedmoDemoBundle:Category:index }
