_demo_category:
    resource: @GedmoDemoBundle/Controller/CategoryController.php
    type:     annotation
    prefix:   /category

_demo_language:
    resource: @GedmoDemoBundle/Controller/LanguageController.php
    type:     annotation
    prefix:   /language

_demo_translation:
    resource: @GedmoDemoBundle/Controller/TranslationController.php
    type:     annotation
    prefix:   /translation
    
_default_demo_index:
    pattern:  /
    defaults: { _controller: GedmoDemoBundle:Category:index }
