imports:
    - { resource: parameters.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
    default_locale:  %locale%
    session:
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug: false
    use_controller: false
    filters:
        cssrewrite: ~
        yui_css: { jar: %kernel.root_dir%/Resources/yui/yuicompressor-2.4.6.jar }
        yui_js: { jar: %kernel.root_dir%/Resources/yui/yuicompressor-2.4.6.jar }

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Doctrine Extension Configuration
stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            tree: true
            timestampable: true
            translatable: true
            sluggable: true
            loggable: true

# Knp Menu Configuration
knp_menu:
    twig: ~
    templating: true
    default_renderer: twig

# Knp Time Configuration
knp_time: ~ 

# Swiftmailer Configuration
swiftmailer: ~
