parameters:
  database_driver:   pdo_mysql
  database_host:     localhost
  database_port:     ~
  database_name:     sfblog
  database_user:     root
  database_password: nimda

  mailer_transport:  smtp
  mailer_host:       localhost
  mailer_user:       ~
  mailer_password:   ~

  locale:            en
  secret:            578g7d4ddg545f666zyu5i
  
  knp_paginator.template.pagination: GedmoBlogBundle:Pagination:sliding.html.twig
  knp_paginator.template.sortable:   GedmoBlogBundle:Pagination:sorting.html.twig
