# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

home:
    pattern:  /
    defaults: { _controller: GedmoBlogBundle:Article:index }

test:
    pattern:  /test/{_locale}
    defaults: { _controller: GedmoDemoBundle:Category:tree, _locale: en }

demo:
    pattern:  /demo/{_locale}
    defaults: { _controller: GedmoDemoBundle:Category:tree, _locale: en }

_blog:
    resource: "@GedmoBlogBundle/Resources/config/routing.yml"

_demo:
    resource: "@GedmoDemoBundle/Resources/config/routing.yml"
    prefix: /demo/{_locale}
