# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

home:
    pattern:  /
    defaults: { _controller: GedmoBlogBundle:Article:index }

_blog:
    resource: "@GedmoBlogBundle/Resources/config/routing.yml"

_demo:
    resource: "@GedmoDemoBundle/Resources/config/routing.yml"
    prefix: /demo/{_locale}