home:
    pattern:  /{_locale}
    defaults: { _controller: GedmoDemoBundle:Category:tree, _locale: en }

test:
    pattern:  /test/{_locale}
    defaults: { _controller: GedmoDemoBundle:Category:tree, _locale: en }

demo:
    pattern:  /demo/{_locale}
    defaults: { _controller: GedmoDemoBundle:Category:tree, _locale: en }

_demo:
    resource: "@GedmoDemoBundle/Resources/config/routing.yml"
    prefix: /{_locale}
